const grid=document.getElementById('grid'),cartBtn=document.getElementById('cartBtn'),cartCount=document.getElementById('cartCount'),cartBox=document.getElementById('cartBox');
let products=[],cart=JSON.parse(localStorage.getItem('nv33cart')||'[]');
const money=v=>'$'+Number(v||0).toFixed(2);
function save(){localStorage.setItem('nv33cart',JSON.stringify(cart));renderCart();}
function selectedColor(id){const active=document.querySelector(`.swatch[data-product="${id}"].active`);return active?active.dataset.color:"";}
function setColor(id,color){document.querySelectorAll(`.swatch[data-product="${id}"]`).forEach(b=>b.classList.remove('active'));const btn=document.querySelector(`.swatch[data-product="${id}"][data-color="${color}"]`);if(btn)btn.classList.add('active');const p=products.find(x=>x.id===id);const img=document.getElementById(`img-${id}`);if(p&&img&&p.images&&p.images[color])img.src=p.images[color];}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p)return;if(!(p.stripePriceId||p.priceId)){alert(`${p.name} is not connected to checkout yet.`);return;}const size=document.getElementById('size-'+id)?.value||'One Size';const color=selectedColor(id)||(p.colors?.[0]?.value||"");cart.push({id:p.id,name:p.name,price:p.price,size,color,stripePriceId:p.stripePriceId||p.priceId||""});save();cartBox.classList.add('show');}
function removeCartItem(index){cart.splice(index,1);save();}
async function checkoutStripe(){if(!cart.length){alert('Your cart is empty.');return;}const missing=cart.filter(i=>!i.stripePriceId);if(missing.length){alert('These items are not connected to Stripe yet: '+missing.map(i=>i.name).join(', '));return;}const lineItems=cart.map(i=>({price:i.stripePriceId,quantity:1,productId:i.id||'',size:i.size||'',color:i.color||''}));try{const res=await fetch('/api/create-checkout-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:lineItems})});const data=await res.json().catch(()=>({}));if(data.url){window.location.href=data.url}else{alert(data.error||'Checkout could not start.')}}catch(err){console.error(err);alert('Checkout could not start. Please contact novanity2026@gmail.com.');}}
function renderCart(){cartCount.textContent=cart.length;const total=cart.reduce((s,i)=>s+Number(i.price||0),0);cartBox.innerHTML=`<h3>Your Cart</h3>${cart.length?cart.map((i,idx)=>`<div class="cartrow"><span>${i.name}<br><small>${[i.color,i.size].filter(Boolean).join(' · ')}</small></span><b>${money(i.price)}</b><button onclick="removeCartItem(${idx})" style="margin-left:8px;border:1px solid #555;background:#111;color:#fff;border-radius:4px">×</button></div>`).join(''):'<p>Your cart is empty.</p>'}<p><b>Total: ${money(total)}</b></p><button class="add" onclick="cart=[];save()">Clear Cart</button><button class="add" onclick="checkoutStripe()">Secure Checkout</button><a class="btn primary" href="checkout.html" style="margin-top:10px;width:100%;justify-content:center">Review Checkout</a>`;}
function swatches(p){if(!p.colors||!p.colors.length)return"";return`<div class="swatches" aria-label="Color options">${p.colors.map((c,i)=>`<button class="swatch ${i===0?'active':''}" data-product="${p.id}" data-color="${c.value}" onclick="setColor('${p.id}','${c.value}')" title="${c.name}" aria-label="${c.name}" style="--swatch:${c.hex}"></button>`).join('')}</div>`;}
function render(f='All'){const items=products.filter(p=>f==='All'||p.category===f||p.tag===f);grid.innerHTML=items.map(p=>{const firstColor=p.colors?.[0]?.value;const initial=(p.images&&firstColor&&p.images[firstColor])?p.images[firstColor]:p.image;const connected=Boolean(p.stripePriceId||p.priceId);return`<article class="card"><span class="badge">${connected?(p.tag||'NEW'):'Coming Soon'}</span><span class="heart">♡</span><div class="imgbox"><img id="img-${p.id}" src="${initial}" alt="${p.name}" loading="lazy" onerror="this.src='assets/logos/crown33.png'"></div><h3>${p.name}</h3><p class="price">${money(p.price)}</p><p class="desc">${p.desc||'Premium Cotton'}</p>${swatches(p)}<select id="size-${p.id}">${(p.sizes||['One Size']).map(s=>`<option>${s}</option>`).join('')}</select><button class="add" ${connected?'':'disabled style="opacity:.55;cursor:not-allowed"'} onclick="addToCart('${p.id}')">${connected?'🛒 Add to Cart':'Coming Soon'}</button></article>`}).join('');}
document.querySelectorAll('[data-filter]').forEach(btn=>{btn.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');render(btn.dataset.filter);};});
cartBtn.onclick=e=>{e.preventDefault();cartBox.classList.toggle('show');};
fetch('data/products.json?v=all-products-stripe').then(r=>r.json()).then(d=>{products=d;render();renderCart();}).catch(err=>{console.error(err);grid.innerHTML='<p style="color:#f6c442">Product catalog could not load.</p>';});